# Generated by Django 4.1.3 on 2022-12-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToolOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('part_num', models.CharField(max_length=25)),
                ('machine_num', models.CharField(max_length=5)),
                ('needed', models.DateTimeField()),
                ('tools', models.TextField()),
                ('comments', models.CharField(max_length=250)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
